### ISSUE TITLE
MOBI build doesn't work on macOS Catalina (10.15.6)

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire-docs#214]
After updating my computer to macOS Catalina (10.15.6) the `quire mobi` command stopped working. It seems as though it's due to the fact that Catalina won't run 32-bit apps. The software Quire uses, **kindlegen**, is 32-bit. See: https://www.mobileread.com/forums/showpost.php?p=3954355&postcount=47.

The suggested fix there is to extract a 64-bit version of kindlegen from the Kindle Previewer software. I tried that myself and was able to successfully build a MOBI file with it, outside of Quire.

Quire installs kindlegen through the [kindlegen node package](https://www.npmjs.com/package/kindlegen). The package grabs the file from the files Amazon hosts and links to at https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211. There is not a publicly available 64-bit version as far as I can tell.

kindlegen is an Amazon tool, and when first researching MOBI file generation for Quire, it was the best and most reliable tool to use. Maybe really even the only one. The Terms of Use prohibit redistributing if I recall, so I'm not sure we could pull the 64-bit version and incorporate it into Quire directly.

**Comment by mantasandri** [comment]
Just started digging a bit into this as well.  Seems like we're not the only ones with the issue:
https://blog.vellum.pub/2019/08/upcoming-changes-to-kindle-generation/.  But, it seems like they were able to get around this, here: https://blog.vellum.pub/2019/10/vellum-2-6-2/ by using [Kindle Previewer 3](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765261), like you suggested.

It seems like the 64 bit executable is stored in: `/Applications/Kindle Previewer 3.app/Contents/lib/fc/bin/kindlegen`.

I'm not seeing anything in regards to redistributing in their [ToS](https://www.amazon.com/gp/feature.html?docId=1000599251), unless I'm just not seeing it?  So we should be able to extract it out.

**Comment by mphstudios** [comment]
The Quire CLI already orchestrates a number of external dependencies that must be downloaded by the user so rather than including this library requiring a user to separately install the Kindle Previewer application seems like a viable way to support MOBI generation going forward.

**Comment by geealbers** [comment]
@mantasandri Thanks for the research! I'd actually never heard of that Vellum publishing tool.

@mphstudios Yes, if we can have users download Kindle Previewer and then have the CLI point to that when running `quire mobi` (without the user having to crack open Previewer in someway) that sounds like a feasible option. I don't like the idea of adding yet another download for folks, but even if Amazon's terms don't expressly prohibition redistribution, they certainly don't expressly license it either so I'd be hesitant to do much.

This should be part of a larger convo on the future of Quire installation as well, right? We at one point floated the idea of hosting the cli as a package that could be installed with `npm install quire`, and I think talked briefly of an optional script that could download and install the other dependencies for users as well? Let's talk about this in the roadmap meetings as soon as we can get past all the Getty pubs feature specs/review stuff. Or maybe sooner?

**Comment by geealbers** [comment]
Just an update. 

[Kindlegen has been officially discontinued](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211) and is no longer available at all. 

On the other hand, [Kindle Previewer has been updated](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765261) and includes a CLI option. In testing it out, I downloaded the Mac pkg version and it was an easy install. Once installed, I was able to convert from an EPUB to a MOBI with `kindlepreviewer output.epub -convert`. There's some more work to be done to figure out some of the workflow and the output options, but this seems like it will be fine generally.

**Comment by hbalenda** [comment]
@geealbers @mphstudios I just tried out the CLI and it looks like it does not currently support specifying the file type as .mobi. According to the docs, `kindlepreviewer <output> -convert` will create a .kpf unless "the book doesn’t
support Enhanced Typesetting", then it will create a .mobi (see: [kindlepreviewer docs section 3](https://kindlepreviewer3.s3.amazonaws.com/UserGuide320_EN.pdf)). There is not currently a way to specify the file format as .mobi unless you use the Kindle Previewer GUI. Is that all right, or is there a reason we want a .mobi specifically?

**Comment by geealbers** [comment]
@hbalenda Yes, I've been trying to figure out that "Enhanced Typesetting" thing, which I only first started seeing with the the recent change to kindlepreviewer. By default, the EPUBs we're putting out with Quire don't seem to support Enhanced Typesetting, but I can't tell why, or how we might change them, or if we'd want to. So, while it seems a little less than ideal to build a process into Quire that could sometimes output a MOBI file and other times output a KPF file and we have no way to know for sure, I also feel fairly certain that until we make some changes to our EPUB output (which btw, isn't a priority, but I'd love to do someday because Pandoc's EPUB output is really janky), kindlepreviewer is just going to keep spitting out MOBI files.

If for some reason we did ever have a choice between the file types, the one thing I'd note is that the kindlepreviewer docs do say that you can't sideload KPF files onto devices, which is actually a downside as we include them in Quire books in part so that readers can do exactly that and download the files and sideload them onto their devices themselves.

**Comment by geealbers** [comment]
Fixed with https://github.com/thegetty/quire/commit/d64dc9519b3accd658f566527abe858c7ddf4e2f
