### ISSUE TITLE
Ability to change contributors format on Splash layouts

### ISSUE THREAD

**Issue by hlj24** [thegetty/quire-docs#353]
Hi, Friends,

I'm using the Splash layout for a number of essays and would like to be able to show only Contributor names. I've tried the YAML described on [this page](https://quire.netlify.app/documentation/contributors/), but it doesn't seem to work for splash -- though it does beautifully for other layouts! Is there a quick fix for this?

Thanks,

Hannah

**Comment by Erin-Cecele** [comment]
This has been resolved. Thank you, @hlj24.
