### ISSUE TITLE
Update documentation to reflect the new repo structure

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#354]
**Redirecting URLs**: 

- [x] Where should new release information be directed? (Ex. [Implementation Considerations](https://quire.netlify.app/documentation/implementation/) links to old repos in [Beta Status & Licensing] section (https://quire.netlify.app/documentation/implementation/#beta-status--licensing).)

- [x] Where should mentions of starter-theme throughout docs be directed (Ex. [Style Customizations](https://quire.netlify.app/documentation/styles-customization/) links to this repo several times https://github.com/thegetty/quire-starter-theme.)

**Concept of Theme & Starter**:

- [x] In multiple places, we mention the "starter kit" and "starter theme." How should this language be updated? (Ex. in Tutorial's [Create a New Project](https://quire.netlify.app/tutorial/#3-create-a-new-project) section. It's also mentioned in [For Developers](https://quire.netlify.app/documentation/for-developers/) section as "Quire starter kit default is `quire-base-theme.`")

- [x] How should the themes folder in a new project be renamed? Same with the quire-starter-theme file within this folder? (This is folder and file are mentioned extensively throughout the documentation, especially in [Style Customizations](https://quire.netlify.app/documentation/styles-customization/), [Font Customizations](https://quire.netlify.app/documentation/fonts-customization/), and [Netlify](https://quire.netlify.app/documentation/netlify/).) 

- [x] Can we remove [Update your theme to newer version](https://quire.netlify.app/documentation/styles-customization/#update-your-theme-to-a-newer-version) and [Change to a new theme](https://quire.netlify.app/documentation/styles-customization/#change-to-a-new-theme) within the Style Customizations sections of the docs? (Similar issue in [Install or Update](https://quire.netlify.app/documentation/install-uninstall/) section.)

- [x] In the [quire/themes/default/README.md](https://github.com/thegetty/quire/blob/main/themes/default/README.md) we mention a "basic" and "modern" theme. Do we want to keep both themes? If so should we mention in documentation?

**Related**

- [x]  In new repo, do we want to stick with the term "default" when referring to our specific starter and our specific theme? (This will affect terminology used in the docs.)

**Comment by geealbers** [comment]
Partway through making these changes, but just wanted to document my approach thus far:

- Quire installs a theme that we should refer to as "the default theme" or "Quire's default theme". We shouldn't ever capitalize it, as in "the Default theme". Default is not the name of a theme, it's just a built-in part of Quire.
- When needing to specify the location of the default theme, or the specific path, it would be: `themes/default`
- Quire uses the concept of "starters" to indicated a body of content (text, images, and metadata resources) structured in a particular way to use as a starting point for a new Quire project. Our "default starter", or "Quire’s default starter" is a sample book that demonstrates a wide range of Quire's capabilities for scholarly monograph and catalogue publishing. Neither "starter" nor "default" would be capitalized.
- Users never see the starter per se, so mostly I think we'll want to refer to it sparingly. Such as in "`quire new` will create a new starter project to use as a seed for your publication."
- In the future the CLI might give them the option to choose a starter, and at that point we would document the idea of a starter more directly. The README for https://github.com/thegetty/quire/tree/main/starters would be the exception where we'd want to more directly define the idea of a Quire starter.
- If we need to refer to the GitHub location of the default theme or the default starter, we would use https://github.com/thegetty/quire/tree/main/themes/default and https://github.com/thegetty/quire/tree/main/starters/default respectively
