### ISSUE TITLE
Homepage: Add consultation text

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#410]
Here's my suggestion. It might be too long though, so I'm open to other options:

"[Contact us](mailto:quire@getty.edu) for a one-on-one consultation to see if Quire is the right tool for your publishing project."

I don't think "[Contact us](mailto:quire@getty.edu) for a one-on-one consultation to determine if Quire is right for you" works because it feels too redundant with the "Why Quire" section.

**Comment by geealbers** [comment]
I started with a shortened phrase at the top of the footer. Design-wise I think it's probably a decent approach for adding a call-out link here, but are one-on-ones too big a benefit to bury in the footer? Should we consider changing "Chat with Our Users" back to something like "Visit the Community Forum" and then change the Community Forum panel with the speech bubble icon to something about the one-on-ones?

<img width="1422" alt="Screen Shot 2021-05-19 at 4 01 25 PM" src="https://user-images.githubusercontent.com/7796401/118895946-fe504280-b8bb-11eb-8c76-65715c53d4c7.png">

**Comment by Erin-Cecele** [comment]
I'm slightly apprehensive about burying the community forum, but at the same time, it's silly the way it is now with the forum getting two mentions. As a selling point, moving consultation to the footer makes the most sense.

**Comment by Erin-Cecele** [comment]
Sorry, I should clarify:

- We should change "Chat with Our Users" to "Visit the Community Forum". 
- We should move the consultation text out of the footer and replace the Community Forum panel with something like "Talk to our Team" or "Schedule a Call" or "Chat with Us" (Get a one-on-one consultation).

**Comment by geealbers** [comment]
Closed with 5556a78
