### ISSUE TITLE
Document adding `references` in page YAML

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire-docs#440]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

We need to document this feature:

> you can add a list of one ore more Author Date reference to the page YAML under `references:` and Quire will add them along with any cited with the `q-cite` shortcode to the bibliography generated at the bottom of the page

It should go in these pages:

https://quire.getty.edu/documentation/citation-bibliographies/
https://quire.getty.edu/documentation/for-developers/#page-api

### What contribution category does your proposal fall under?

Propose/write new section

**Comment by Erin-Cecele** [comment]
@geealbers will this also be available in 11ty?

**Comment by Erin-Cecele** [comment]
Test that this is working before adding it to the documentation.

**Comment by Erin-Cecele** [comment]
This is related to the main [`quire` repo issue #654 ](https://github.com/thegetty/quire/issues/654).

**Comment by Erin-Cecele** [comment]
Addressed in PR #691
