### ISSUE TITLE
Documentation: Add word on "Get Started" page

### ISSUE THREAD

**Issue by dimrkh** [thegetty/quire-docs#464]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

In the `get-started.md` file, add "a" before "step-by-step introduction" on the "[Get Started](https://quire.getty.edu/documentation/getting-started/)" page.

### What contribution category does your proposal fall under?

Copyedit text

### Supporting Information

<img width="836" alt="Screen Shot 2021-11-05 at 8 47 48 AM" src="https://user-images.githubusercontent.com/90800713/140539084-8d008b78-48c2-474b-8533-f3a0967c0452.png">

**Comment by doboianh** [comment]
Hey guy, can i try it ?

**Comment by Erin-Cecele** [comment]
@doboianh Absolutely! I will assign this issue to you now. If you haven't already, please read our [Contributing Guidelines](https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md) before proceeding. Thank you in advance for your contribution.

**Comment by Erin-Cecele** [comment]
Hi @doboianh. I am going to remove you as an assignee form this issue, as it's been a while since we've heard from you. If you'd like to come back and work on it in the future (and someone else hasn't already tackled it) just let us know! Thank you.

**Comment by Erin-Cecele** [comment]
This was fixed in the v1 docs
