### ISSUE TITLE
Documentation: Edit words on "Get Started" page

### ISSUE THREAD

**Issue by dimrkh** [thegetty/quire-docs#465]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

In the `get-started.md` file, edit hyperlinked text, "_Tutorial: Quire Basics_," to "_Quire Basics Tutorial_" on "[Get Started](https://quire.getty.edu/documentation/getting-started/)" page, to match the title of the "[Quire Basics Tutorial](https://quire.getty.edu/learn/tutorial/)" page. 

### What contribution category does your proposal fall under?

Copyedit text

### Supporting Information

<img width="836" alt="Screen Shot 2021-11-05 at 8 47 48 AM" src="https://user-images.githubusercontent.com/90800713/140539933-cb9f9f92-e429-438a-ab50-bfc45b5661af.png">

**Comment by Erin-Cecele** [comment]
This was completed in the v1 docs
