### ISSUE TITLE
Italicize words on "What Is Quire?" page

### ISSUE THREAD

**Issue by dimrkh** [thegetty/quire-docs#466]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Italicize "Implementation Considerations" in the last bullet point under "[Is Quire Right for You?](https://quire.getty.edu/about/quire/#is-quire-right-for-you)" on the "What Is Quire?" page, per the [Quire Website & Documentation Style Guide](https://github.com/thegetty/quire-docs/wiki/Quire-Website-&-Documentation-Style-Guide).  

### What contribution category does your proposal fall under?

Copyedit text

### Supporting Information

<img width="751" alt="Screen Shot 2021-11-05 at 9 03 49 AM" src="https://user-images.githubusercontent.com/90800713/140541451-91142b7b-b95d-4c43-ac0d-9125ef1ecc18.png">

**Comment by Erin-Cecele** [comment]
This has been completed as part of my GitHub tutorial for staff
