### ISSUE TITLE
Edit text on "Project Management with GitHub" page

### ISSUE THREAD

**Issue by dimrkh** [thegetty/quire-docs#469]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Delete hyphen between "blue" and "button" [to read "blue button"] in text for Step 4 under "Host Your Project's Code on GitHub" section on "[Project Management with GitHub](https://quire.getty.edu/documentation/github/)" page.  

### What contribution category does your proposal fall under?

Fix typo/broken link

### Supporting Information

![Screen Shot 2021-11-08 at 12 54 54 PM](https://user-images.githubusercontent.com/90800713/140816757-3e635dcd-ee8c-4da7-886a-bd6bdf17008c.png)

**Comment by leslie-martinez15** [comment]
I am going to fix this issue

**Comment by leslie-martinez15** [comment]
This issue is resolved with PR #525
