### ISSUE TITLE
The windows-build-tools package has been deprecated and may need to be removed from install steps

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire-docs#477]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

For our Windows install instructions we have users install windows-build-tools, but it's recently been deprecated: https://www.npmjs.com/package/windows-build-tools. Some testing should be done to see if it's no longer needed and if so, that step can be removed from the install guidelines.

### What contribution category does your proposal fall under?

Other

**Comment by Erin-Cecele** [comment]
This was done in the v1 docs
