### ISSUE TITLE
Docs Update: Implementation Considerations 

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#530]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

- [x] Remove information about signing up and alter license language
- [x] Add mention of javascript (and liquid?) to "skill requirements"
- [x] Remove Prince XML from "affiliated costs" 
- [x] Add info about contacting us for freelance developer recommendations.
- [x] Remove mention of limited beta under "versioning"
- [x] Add correct license information 

### What contribution category does your proposal fall under?

Copyedit text

### Supporting Information

This is the docs page: https://quire.getty.edu/documentation/implementation/ 

These edits are related to the 11ty Quire update and forthcoming open-source launch.

**Comment by Erin-Cecele** [comment]
@geealbers Edits to this page are just about ready for review. Do we know what licensing language we plan on using once we launch as open source? If not, I will keep this issue open. 

In the meantime, I removed the previous language:

> For a free license to use Quire for your publication projects, and for additional access to support, [please sign up](https://docs.google.com/forms/d/e/1FAIpQLScKOJEq9ivhwizmdazjuhxBII-s-5SUsnerWmyF8VteeeRBhA/viewform).

> A Quire license enables users to create publications with Quire and distribute as they see fit. Users can modify the default theme in any way that suits their needs. However, we ask that users **don’t redistribute Quire itself.**

**Comment by geealbers** [comment]
We'll be releasing Quire under a BSD 3-Clause license if you want to include that language: https://opensource.org/licenses/BSD-3-Clause. The license will also be included in the repo as a LICENSE.md file. And I thought this was a pretty good breakdown of the different license types: https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633.

**Comment by Erin-Cecele** [comment]
Closed by PR #565

**Comment by Erin-Cecele** [comment]
Closed by PR #565
