### ISSUE TITLE
Switch word order in Figure Images documentation

### ISSUE THREAD

**Issue by dimrkh** [thegetty/quire-docs#548]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Switch word order "can you" to "you can" in first sentence of the #add-tables subsection of the Figure Images section of the Documentation [here](https://quire.getty.edu/documentation/figure-images/#add-tables). 

It should read: "In addition inserting tables in your project as Markdown, **you can** also embed tables as HTML files..." 

### What contribution category does your proposal fall under?

Copyedit text

### Supporting Information

<img width="526" alt="Screen Shot 2022-08-01 at 5 39 43 PM" src="https://user-images.githubusercontent.com/90800713/182267670-6cf1f19f-fefa-41e0-a98b-f6af283cd7e2.png">

**Comment by Erin-Cecele** [comment]
Thank you @dimrkh for posting this issue!
