### ISSUE TITLE
V1 Docs: Add {% %} to shortcode references - GLOBAL

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#550]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

@geealbers I propose that when referencing shortcodes, because we no longer have the q- prefix, we should wrap the shortcode reference in `{% %}`. For example:

"When using the `{% bibliography %} shortcode..." 

### What contribution category does your proposal fall under?

Copyedit text

**Comment by geealbers** [comment]
@Erin-Cecele yes, good idea!

**Comment by Erin-Cecele** [comment]
@geealbers Can this be done as a global fix (regex) or should it be done manually?

**Comment by Erin-Cecele** [comment]
Adding a note that this needs to be done manually and cannot be a global fix with regex. Leaving the issue open so I remember to double check everything.

**Comment by Erin-Cecele** [comment]
This has been completed
