### ISSUE TITLE
V1 Docs: Warning and Tip Shortcodes

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#561]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Confirm if we will still use these class shortcodes and then globally replace them:

{{< q-class "box tip" >}}

{{< /q-class >}}

and 

{{< q-class " box warning" >}}

{{< /q-class >}}

### What contribution category does your proposal fall under?

Copyedit text

**Comment by Erin-Cecele** [comment]
@geealbers Will using these shortcodes to create the tips in the docs still work though? Or will I get an error?

**Comment by geealbers** [comment]
Yes, we're going to leave the whole Quire site (including the docs) in the Hugo version for now, so they'll still work. We'll have to rewrite them when we port everything over to the 11ty version.

**Comment by Erin-Cecele** [comment]
Closing this issue because it's related to a larger overhaul that will happen when we transition the website from Hugo to 11ty.
