### ISSUE TITLE
Learn: Edit Cheatsheet

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#575]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Update the shortcodes specifically: https://quire.getty.edu/learn/cheatsheet/#shortcodes

### What contribution category does your proposal fall under?

Copyedit text

**Comment by Erin-Cecele** [comment]
This page is currently hidden until it's updated

**Comment by geealbers** [comment]
@jenpark-getty, can you please take on this task to update the Quire Cheatsheet page that now lives at: https://quire.getty.edu/resources/cheatsheet/? It's currently geared to the v0 version of Quire and we need to move it to v1. Here's what needs to be done:

- [ ] Update the illustrated Design Guide following the edits made to this PDF: [quire-design-guide--v1-edits.pdf](https://github.com/thegetty/quire-docs/files/12561879/quire-design-guide--v1-edits.pdf). I'll point you to the source files for the Guide on our department server.
- [ ] Add the updated Guide to the `quire-docs` repo, being sure to update both the figure image version and the downloadable PDF
- [ ] Edit the Markdown page. In the YAML section there is a reference to `weight:` that should be `order:`, and to the `data` folder that is now `_data`. And then in the Shortcodes section there's a lot that needs updating. Take your best stab at it and then @Erin-Cecele or I can make any comments/edits when we review your pull request.

Thanks!
