### ISSUE TITLE
Adding summary to the Tutorial

### ISSUE THREAD

**Issue by Cmillhauser** [thegetty/quire-docs#585]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

I wanted to add a little more summary to the tutorial so that new readers have some more orientation as they begin working with Quire.

### What contribution category does your proposal fall under?

Copyedit text

**Comment by Erin-Cecele** [comment]
Hi @Cmillhauser. Great issue to take on! I just want to clarify for record keeping that you are making changes to the V-1 tutorial. I look forward to seeing your work!

**Comment by Cmillhauser** [comment]
Yes! Thank you Erin!
