### ISSUE TITLE
V1 Docs: Use single quotes in shortcodes - GLOBAL

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#594]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Use single quotes to surround id values in shortcodes - scan v1 docs to make this correction. There may be a solution with regex.

### What contribution category does your proposal fall under?

Copyedit text

**Comment by Erin-Cecele** [comment]
@geealbers I was inconsistent in using single quotes in shortcode examples throughout the v1 docs. Is there a regex I can use for this or should it be done by hand?

**Comment by geealbers** [comment]
Yes, regex should certainly work. Can you share some examples of the ones that you will want to change?

**Comment by Erin-Cecele** [comment]
Well, @geealbers, I actually can't find any examples. So either they are few and far between, and I'll have to correct them when I come across them, or I was getting mixed up with the old style of shortcodes dispersed throughout the docs—closing this issue regardless.
