### ISSUE TITLE
Improve this page missing from docs pages

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#620]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

bring back the button that allows readers to contribute to the docs. Reference is closed PR #408.

### What contribution category does your proposal fall under?

Other

**Comment by geealbers** [comment]
closed with PR #621
