### ISSUE TITLE
Please drop the non-commercial license restriction

### ISSUE THREAD

**Issue by davelab6** [thegetty/quire-docs#624]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Now the project code is fully libre, it is a great disappointment that the docs are restricted to non commerical use and modifications; since my employee contract says my work week is 24/7 and all my work is owned by my employer, I am blocked from contribution until the anti commercial restriction is removed, and so won't adopt Quire 

### What contribution category does your proposal fall under?

Other

**Comment by geealbers** [comment]
Done with PR #626

**Comment by davelab6** [comment]
Amazing!! Thank you so much ❤️
