### ISSUE TITLE
About: How it Works 

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#649]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Fix typo with parens:
<img width="782" alt="Screen Shot 2023-02-07 at 6 33 59 PM" src="https://user-images.githubusercontent.com/62075223/217414023-289dff41-f20f-4625-a2d6-c3686a9d3a67.png">

### What contribution category does your proposal fall under?

Copyedit text

**Comment by dawei-wang** [comment]
Hi I would like to work on this issue

**Comment by Erin-Cecele** [comment]
Hi @dawei-wang wonderful. Please go ahead and make the correction!
