### ISSUE TITLE
V1 Docs: Add 360 Rotating Image Instructions 

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#684]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Add instructions for this new Quire feature debuting in Getty's [_French Silver_ ](https://www.getty.edu/publications/french-silver/)collection catalogue.

### What contribution category does your proposal fall under?

Propose/write new section

**Comment by geealbers** [comment]
Done!
