### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by pselinsk** [thegetty/quire-docs#703]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

There is a broken link on one of your resources pages: [https://quire.getty.edu/resources/resources/](https://urldefense.com/v3/__https://quire.getty.edu/resources/resources/__;!!IBzWLUs!VLnlo1xq39MtgvUWIAKMkycf_FpGg0SD7vcEl7diMlTNaLn3D7hhOUAFbAdmytSFeqQ4iGHzujYqqU_SE6ZvCpA$) Under HTML and CSS, the top link Interneting is Hard seems to not work.

### What contribution category does your proposal fall under?

Other

**Comment by Erin-Cecele** [comment]
Thank you, @pselinsk, for spotting this and opening an issue. This issue was addressed in PR #705
