### ISSUE TITLE
Update/enhance instructions for installing the proper version of Node.js

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire-docs#734]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

I've posted a Jira ticket ([DEV-18051](https://jira.getty.edu/browse/DEV-18051))so we can get Quire updated to the current Node LTS version (v20), but until that happens, it might be prudent update our documentation to point users to download Quire's current supported version of Node v18?

And/or I also noticed that the Node website how has some pretty handy tools for ...

- finding the correct installer for older versions of Node: https://nodejs.org/en/download/prebuilt-installer
- and for installing node with a package manager: https://nodejs.org/en/download/package-manager

And both of these support both macOS and Windows users. So maybe worth pointing to these from our docs?

### What contribution category does your proposal fall under?

Copyedit text

**Comment by Erin-Cecele** [comment]
Addressed in PR #730
